# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTextEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")

        # --- Горизонтальный контейнер для двух экземпляров ---
        self.instances_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.instances_layout = QtWidgets.QHBoxLayout(self.instances_container)
        self.instances_layout.setObjectName("instances_layout")
        self.main_layout.addWidget(self.instances_container)

        # --- Экземпляр 1 ---
        self.instance1_groupbox = QtWidgets.QGroupBox(parent=self.instances_container)
        self.instance1_groupbox.setObjectName("instance1_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.instance1_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        # --- Окно Управления (Экземпляр 1) ---
        self.control_groupbox = QtWidgets.QGroupBox(parent=self.instance1_groupbox)
        self.control_groupbox.setObjectName("control_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.control_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.control_groupbox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.port_combo = QtWidgets.QComboBox(parent=self.control_groupbox)
        self.port_combo.setObjectName("port_combo")
        self.verticalLayout_2.addWidget(self.port_combo)
        self.label_3 = QtWidgets.QLabel(parent=self.control_groupbox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.port_combo_2 = QtWidgets.QComboBox(parent=self.control_groupbox)
        self.port_combo_2.setObjectName("port_combo_2")
        self.verticalLayout_2.addWidget(self.port_combo_2)
        self.label_2 = QtWidgets.QLabel(parent=self.control_groupbox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.parity_combo = QtWidgets.QComboBox(parent=self.control_groupbox)
        self.parity_combo.setObjectName("parity_combo")
        self.verticalLayout_2.addWidget(self.parity_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_button = QtWidgets.QPushButton(parent=self.control_groupbox)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(parent=self.control_groupbox)
        self.disconnect_button.setObjectName("disconnect_button")
        self.horizontalLayout.addWidget(self.disconnect_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.control_groupbox, 0, 1, 1, 1)
        
        # --- Окно Ввода (Экземпляр 1) ---
        self.input_groupbox = QtWidgets.QGroupBox(parent=self.instance1_groupbox)
        self.input_groupbox.setObjectName("input_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.input_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_text = QtWidgets.QTextEdit(parent=self.input_groupbox)
        self.input_text.setObjectName("input_text")
        self.verticalLayout_3.addWidget(self.input_text)
        
        self.send_button = QtWidgets.QPushButton(parent=self.input_groupbox)
        self.send_button.setObjectName("send_button")
        self.verticalLayout_3.addWidget(self.send_button)

        self.label_prepared_data = QtWidgets.QLabel(parent=self.input_groupbox)
        self.label_prepared_data.setObjectName("label_prepared_data")
        self.verticalLayout_3.addWidget(self.label_prepared_data)
        
        self.pre_send_data_window = QtWidgets.QTextEdit(parent=self.input_groupbox)
        self.pre_send_data_window.setReadOnly(True)
        self.pre_send_data_window.setObjectName("pre_send_data_window")
        self.verticalLayout_3.addWidget(self.pre_send_data_window)
        self.gridLayout_2.addWidget(self.input_groupbox, 0, 0, 1, 1)
        
        # --- Окно Вывода (Экземпляр 1) ---
        self.output_groupbox = QtWidgets.QGroupBox(parent=self.instance1_groupbox)
        self.output_groupbox.setObjectName("output_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.output_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_text = QtWidgets.QPlainTextEdit(parent=self.output_groupbox)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.verticalLayout.addWidget(self.output_text)
        self.gridLayout_2.addWidget(self.output_groupbox, 1, 0, 1, 1)
        
        # --- Окно Состояния (Экземпляр 1) ---
        self.status_groupbox = QtWidgets.QGroupBox(parent=self.instance1_groupbox)
        self.status_groupbox.setObjectName("status_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.status_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.speed_status_label = QtWidgets.QLabel(parent=self.status_groupbox)
        self.speed_status_label.setObjectName("speed_status_label")
        self.verticalLayout_4.addWidget(self.speed_status_label)
        self.sent_bytes_status_label = QtWidgets.QLabel(parent=self.status_groupbox)
        self.sent_bytes_status_label.setObjectName("sent_bytes_status_label")
        self.verticalLayout_4.addWidget(self.sent_bytes_status_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.status_groupbox, 1, 1, 1, 1)
        
        self.instances_layout.addWidget(self.instance1_groupbox)

        # --- Экземпляр 2 ---
        self.instance2_groupbox = QtWidgets.QGroupBox(parent=self.instances_container)
        self.instance2_groupbox.setObjectName("instance2_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.instance2_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        # --- Окно Управления (Экземпляр 2) ---
        self.control_groupbox_2 = QtWidgets.QGroupBox(parent=self.instance2_groupbox)
        self.control_groupbox_2.setObjectName("control_groupbox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.control_groupbox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.control_groupbox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.port_combo_tab2 = QtWidgets.QComboBox(parent=self.control_groupbox_2)
        self.port_combo_tab2.setObjectName("port_combo_tab2")
        self.verticalLayout_6.addWidget(self.port_combo_tab2)
        self.label_5 = QtWidgets.QLabel(parent=self.control_groupbox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.port_combo_2_tab2 = QtWidgets.QComboBox(parent=self.control_groupbox_2)
        self.port_combo_2_tab2.setObjectName("port_combo_2_tab2")
        self.verticalLayout_6.addWidget(self.port_combo_2_tab2)
        self.label_6 = QtWidgets.QLabel(parent=self.control_groupbox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.parity_combo_tab2 = QtWidgets.QComboBox(parent=self.control_groupbox_2)
        self.parity_combo_tab2.setObjectName("parity_combo_tab2")
        self.verticalLayout_6.addWidget(self.parity_combo_tab2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connect_button_tab2 = QtWidgets.QPushButton(parent=self.control_groupbox_2)
        self.connect_button_tab2.setObjectName("connect_button_tab2")
        self.horizontalLayout_2.addWidget(self.connect_button_tab2)
        self.disconnect_button_tab2 = QtWidgets.QPushButton(parent=self.control_groupbox_2)
        self.disconnect_button_tab2.setObjectName("disconnect_button_tab2")
        self.horizontalLayout_2.addWidget(self.disconnect_button_tab2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.gridLayout_3.addWidget(self.control_groupbox_2, 0, 1, 1, 1)
        
        # --- Окно Ввода (Экземпляр 2) ---
        self.input_groupbox_2 = QtWidgets.QGroupBox(parent=self.instance2_groupbox)
        self.input_groupbox_2.setObjectName("input_groupbox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.input_groupbox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.input_text_2 = QtWidgets.QTextEdit(parent=self.input_groupbox_2)
        self.input_text_2.setObjectName("input_text_2")
        self.verticalLayout_7.addWidget(self.input_text_2)

        self.send_button_2 = QtWidgets.QPushButton(parent=self.input_groupbox_2)
        self.send_button_2.setObjectName("send_button_2")
        self.verticalLayout_7.addWidget(self.send_button_2)

        self.label_prepared_data_2 = QtWidgets.QLabel(parent=self.input_groupbox_2)
        self.label_prepared_data_2.setObjectName("label_prepared_data_2")
        self.verticalLayout_7.addWidget(self.label_prepared_data_2)

        self.pre_send_data_window_2 = QtWidgets.QTextEdit(parent=self.input_groupbox_2)
        self.pre_send_data_window_2.setReadOnly(True)
        self.pre_send_data_window_2.setObjectName("pre_send_data_window_2")
        self.verticalLayout_7.addWidget(self.pre_send_data_window_2)
        self.gridLayout_3.addWidget(self.input_groupbox_2, 0, 0, 1, 1)
        
        # --- Окно Вывода (Экземпляр 2) ---
        self.output_groupbox_2 = QtWidgets.QGroupBox(parent=self.instance2_groupbox)
        self.output_groupbox_2.setObjectName("output_groupbox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.output_groupbox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.output_text_tab2 = QtWidgets.QPlainTextEdit(parent=self.output_groupbox_2)
        self.output_text_tab2.setReadOnly(True)
        self.output_text_tab2.setObjectName("output_text_tab2")
        self.verticalLayout_8.addWidget(self.output_text_tab2)
        self.gridLayout_3.addWidget(self.output_groupbox_2, 1, 0, 1, 1)
        
        # --- Окно Состояния (Экземпляр 2) ---
        self.status_groupbox_2 = QtWidgets.QGroupBox(parent=self.instance2_groupbox)
        self.status_groupbox_2.setObjectName("status_groupbox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.status_groupbox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.speed_status_label_tab2 = QtWidgets.QLabel(parent=self.status_groupbox_2)
        self.speed_status_label_tab2.setObjectName("speed_status_label_tab2")
        self.verticalLayout_9.addWidget(self.speed_status_label_tab2)
        self.sent_bytes_status_label_tab2 = QtWidgets.QLabel(parent=self.status_groupbox_2)
        self.sent_bytes_status_label_tab2.setObjectName("sent_bytes_status_label_tab2")
        self.verticalLayout_9.addWidget(self.sent_bytes_status_label_tab2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.gridLayout_3.addWidget(self.status_groupbox_2, 1, 1, 1, 1)

        self.instances_layout.addWidget(self.instance2_groupbox)
        
        # --- Отладочное Окно ---
        self.debug_groupbox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.debug_groupbox.setObjectName("debug_groupbox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.debug_groupbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.debug_text = QtWidgets.QPlainTextEdit(parent=self.debug_groupbox)
        self.debug_text.setReadOnly(True)
        self.debug_text.setObjectName("debug_text")
        self.verticalLayout_5.addWidget(self.debug_text)
        self.main_layout.addWidget(self.debug_groupbox)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COM Communicator"))
        self.instance1_groupbox.setTitle(_translate("MainWindow", "Экземпляр 1"))
        self.control_groupbox.setTitle(_translate("MainWindow", "Окно управления"))
        self.label.setText(_translate("MainWindow", "Порт для передачи (Tx):"))
        self.label_3.setText(_translate("MainWindow", "Порт для приема (Rx):"))
        self.label_2.setText(_translate("MainWindow", "Проверка на четность (Parity):"))
        self.connect_button.setText(_translate("MainWindow", "Подключить"))
        self.disconnect_button.setText(_translate("MainWindow", "Отключить"))
        self.input_groupbox.setTitle(_translate("MainWindow", "Окно ввода"))
        self.send_button.setText(_translate("MainWindow", "Отправить"))
        self.label_prepared_data.setText(_translate("MainWindow", "Данные для отправки:"))
        self.output_groupbox.setTitle(_translate("MainWindow", "Окно вывода"))
        self.status_groupbox.setTitle(_translate("MainWindow", "Окно состояния"))
        self.speed_status_label.setText(_translate("MainWindow", "Скорость порта: -"))
        self.sent_bytes_status_label.setText(_translate("MainWindow", "Количество переданных байт: 0"))
        
        self.instance2_groupbox.setTitle(_translate("MainWindow", "Экземпляр 2"))
        self.control_groupbox_2.setTitle(_translate("MainWindow", "Окно управления"))
        self.label_4.setText(_translate("MainWindow", "Порт для передачи (Tx):"))
        self.label_5.setText(_translate("MainWindow", "Порт для приема (Rx):"))
        self.label_6.setText(_translate("MainWindow", "Проверка на четность (Parity):"))
        self.connect_button_tab2.setText(_translate("MainWindow", "Подключить"))
        self.disconnect_button_tab2.setText(_translate("MainWindow", "Отключить"))
        self.input_groupbox_2.setTitle(_translate("MainWindow", "Окно ввода"))
        self.send_button_2.setText(_translate("MainWindow", "Отправить"))
        self.label_prepared_data_2.setText(_translate("MainWindow", "Данные для отправки:"))
        self.output_groupbox_2.setTitle(_translate("MainWindow", "Окно вывода"))
        self.status_groupbox_2.setTitle(_translate("MainWindow", "Окно состояния"))
        self.speed_status_label_tab2.setText(_translate("MainWindow", "Скорость порта: -"))
        self.sent_bytes_status_label_tab2.setText(_translate("MainWindow", "Количество переданных байт: 0"))
        
        self.debug_groupbox.setTitle(_translate("MainWindow", "Отладочное окно"))